### ISSUE TITLE
チャット機能_設計

### ISSUE THREAD

**Issue by bayamasa** [no-keisuke/project-ragnarok#3]
https://www.notion.so/5f8ba8acd85d4428ad3bfad97bfeba35?v=19a43ae4a6b84d21bba615c05cbb6d0d&p=97a79d2f8e894e678fddb4407e355c56

**Comment by ACkubo** [comment]
https://www.hiramine.com/programming/chat_django_channels/index.html

**Comment by bayamasa** [comment]
資料作成済みのためクローズ
